
package employ_payroll;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatDarkLaf; // Or FlatLightLaf if you prefer light mode

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author beye
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        stylingUI();
    }
private void stylingUI() {
    // 1. Set Frame Background (Modern Slate Gray from maw12.jpg)
    this.getContentPane().setBackground(new java.awt.Color(237, 242, 246));

    // 2. Style the Login Panel (White box)
    loginPanel.setBackground(java.awt.Color.WHITE);
    loginPanel.putClientProperty("FlatLaf.style", "arc: 30");

    // 3. Define Global Font
    java.awt.Font segoeFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14);

    // 4. Style Username (txtUser)
    txtUser.setFont(segoeFont);
    txtUser.putClientProperty("JTextField.placeholderText", "Username");
    txtUser.putClientProperty("JTextField.arc", 15);

    // 5. Style Password (txtPass)
    txtPass.setFont(segoeFont);
    txtPass.putClientProperty("JTextField.placeholderText", "Password");
    txtPass.putClientProperty("JTextField.arc", 15);
    txtPass.putClientProperty("JTextField.showRevealButton", true); 

    // 6. Style Login Button (Modern Blue)
    btnLogin.setBackground(new java.awt.Color(61, 107, 150));
    btnLogin.setForeground(java.awt.Color.WHITE);
    btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14));
    btnLogin.putClientProperty("JButton.buttonType", "roundRect");
    btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
} /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        loginPanel = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(237, 242, 246));
        setMaximumSize(new java.awt.Dimension(950, 690));
        setMinimumSize(new java.awt.Dimension(950, 690));
        setPreferredSize(new java.awt.Dimension(950, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        loginPanel.setForeground(new java.awt.Color(204, 204, 204));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setBackground(new java.awt.Color(237, 242, 246));
        loginPanel.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 400, 45));

        txtPass.setBackground(new java.awt.Color(237, 242, 246));
        txtPass.addActionListener(this::txtPassActionPerformed);
        loginPanel.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 400, 45));

        btnLogin.setBackground(new java.awt.Color(61, 107, 150));
        btnLogin.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        loginPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 400, 45));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(44, 62, 80));
        jLabel3.setText("Login");
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 200, 40));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 140, 500, 400));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/gear1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 80, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(28, 55, 90));
        jLabel4.setText(" Employee payroll System ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 400, 40));

        jPanel1.setBackground(new java.awt.Color(209, 216, 224));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("04 May 2026");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 890, 50));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
                                       
    String user = txtUser.getText();
    String pass = new String(txtPass.getPassword()); // Converts dots to text for checking

    // For now, let's use a simple hardcoded login
    if (user.equals("admin") && pass.equals("1234")) {
        JOptionPane.showMessageDialog(this, "Login Successful!");
        
        // Open the Main Payroll Frame
        MainPayrollFrame main = new MainPayrollFrame();
        main.setVisible(true);
        
        // Close the Login Frame
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid Username or Password", "Login Error", JOptionPane.ERROR_MESSAGE);
        txtPass.setText(""); // Clear password field for retry
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    // 1. Setup the FlatLaf Look and Feel
    com.formdev.flatlaf.FlatLightLaf.setup();

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        new LoginFrame().setVisible(true);
    });

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
